### ISSUE TITLE
Suggest only approved investor can approve allowance and  transfer tokens

### ISSUE THREAD

**Issue by ryu9827** [tikonoff/gifto#23]
https://github.com/tikonoff/gifto/blob/a657b733da4ecf5f93caacbb900bb3c39237c216/contracts/Gifto.sol#L328

https://github.com/tikonoff/gifto/blob/a657b733da4ecf5f93caacbb900bb3c39237c216/contracts/Gifto.sol#L304

Suggest only approved investor can approve allowance and  transfer tokens. Or if you remove a investor out from the list, they still can call approve() and transferFrom()

**Comment by tikonoff** [comment]
That's not an issue. Everything is working perfect, as expected.
